Criando estrutura payer
LuizFilipeLT/Rocket-Charger pull request #12
Opened 2022-04-18 15:38 UTC by LuizFilipeLT

Aguardando outro PR: https://github.com/LuizFilipeLT/Rocket-Charger/pull/7

Realizado criação da funcionalidade create, save e list do payer, estilização e criação mais detalhada do front será feita e adicionada após funcionalidades estarem ativas.
![Peek 18-04-2022 12-37](https://user-images.githubusercontent.com/94563876/163833086-414eeabc-73c2-4be5-ba46-195ea0c4ad3e.gif)

2022-04-22 16:59 UTC, geanfarias commented on grails-app/assets/javascripts/payerCreateSave/payerPostalCode-api.js
> +    return;
precisa?

2022-04-22 17:00 UTC, geanfarias commented on grails-app/assets/javascripts/payerCreateSave/payerPostalCode-api.js
> +  let city = document.querySelector("#city");
não acho uma boa abordagem porque possa ser que esses campos não existam na tela, eu verificaria se eles existem para poder continuar

2022-04-22 17:00 UTC, geanfarias commented on grails-app/controllers/com/rocketcharger/domain/PayerController.groovy
> +    }
```suggestion
    def create() { }
```

2022-04-22 17:01 UTC, geanfarias commented on grails-app/controllers/com/rocketcharger/domain/PayerController.groovy
> +            render([success: false, message: "Ocorreu um erro"] as JSON)
se tu estás retornando uma propriedade chamada "message" você usa ela, lá no js vc está setando a mensagem novamente e não usando a informação que está enviando na requisição

2022-04-22 17:01 UTC, geanfarias commented on grails-app/domain/com/rocketcharger/domain/Payer.groovy
> +        id size: 10..10, nulllable: true
unique?

2022-04-22 17:03 UTC, geanfarias commented on grails-app/views/payer/create.gsp
> +            <input type="text" name="province" id="province" placeholder="Bairro"><br>
province?

2022-04-25 12:05 UTC, LuizFilipeLT commented on grails-app/assets/javascripts/payerCreateSave/payerPostalCode-api.js
> +    return;
Realizado remoção do return.

2022-04-25 13:09 UTC, LuizFilipeLT commented on grails-app/domain/com/rocketcharger/domain/Payer.groovy
> +        id size: 10..10, nulllable: true
Na verdade optamos por não ter constraints no momento, realizamos remoção.

2022-04-28 03:27 UTC, geanfarias commented on grails-app/assets/javascripts/payerCreateSave/payerCreateSave.js
> +    $.post("/payer/save", customer, function (response) {
captura essa informação do action do form ou do value de um input hidden

2022-04-28 03:28 UTC, geanfarias commented on grails-app/assets/javascripts/payerCreateSave/payerPostalCode-api.js
> +document.querySelector("form").addEventListener("submit", function (event) {
por que num você cripu função a parte e aqui você criou a função no parâmetro? não seria interessante padronizar?

2022-04-28 03:32 UTC, geanfarias commented on grails-app/views/payer/_list.gsp
> +<g:if test="${payerList?.size() > 0}">
muito bom o uso da propriedade para verificar se existe para poder renderizar a lsita, parabéns

2022-04-28 03:33 UTC, geanfarias commented on grails-app/views/payer/_list.gsp
> +    <div><strong>Não há pagadores.</strong></div>
que tal pensar numa forma padrão de mostrar algo quando não tiver informação para renderizar?

2022-04-28 03:35 UTC, geanfarias commented
todos os prs estão como "aguardando outro pr", sendo que não estão mais... excluam a branch do pr https://github.com/LuizFilipeLT/Rocket-Charger/pull/7 ou mudem a base para a `main`

2022-04-28 12:44 UTC, LuizFilipeLT commented on grails-app/assets/javascripts/payerCreateSave/payerCreateSave.js
> +    $.post("/payer/save", customer, function (response) {
Opa, realizado alteração.

2022-04-28 12:46 UTC, LuizFilipeLT commented on grails-app/views/payer/_list.gsp
> +<g:if test="${payerList?.size() > 0}">
José que teve a ideia, agradecemos o elogio.

2022-04-28 13:36 UTC, LuizFilipeLT commented on grails-app/assets/javascripts/payerCreateSave/payerPostalCode-api.js
> +document.querySelector("form").addEventListener("submit", function (event) {
Realizado padronização.

2022-04-28 13:44 UTC, devJoseOtavio commented on grails-app/views/payer/_list.gsp
> +    <div><strong>Não há pagadores.</strong></div>
Como ainda não fizemos a parte de front optamos por renderizar esta informação para ter um controle melhor do nosso back, assim que começarmos o front iremos remover essas linhas pois saberemos se terá listas cadastradas ou não

2022-05-02 13:45 UTC, LuizFilipeLT commented on grails-app/assets/javascripts/payer/payerCreateSave.js
> +      if (response.success) {
Realizado a inclusão de um Alert informando erro.

2022-05-03 19:13 UTC, Yuri-Ferrari requested changes

2022-05-03 19:13 UTC, Yuri-Ferrari commented on grails-app/controllers/com/rocketcharger/domain/PayerController.groovy
> +import static org.springframework.http.HttpStatus.*
Esse import é utilizado? Se não, pode ser removido, código limpo é vida

2022-05-03 19:13 UTC, Yuri-Ferrari commented on grails-app/domain/com/rocketcharger/domain/Payer.groovy
> +    String state
Sugiro colocar uma linha vazia entre cada uma dessas props, em domínios grandes isso facilita muito a leitura e por isto vale padronizar para todos os domínios, até os pequenos que é o caso desse.

2022-05-03 19:13 UTC, Yuri-Ferrari commented on grails-app/views/layouts/main.gsp
> +
Não há necessidade de duas linhas vazias na sequência.

2022-05-03 19:13 UTC, Yuri-Ferrari commented on grails-app/controllers/com/rocketcharger/domain/PayerController.groovy
> +            payerService.save(params)
É importantíssimo validar no backend as informações recebidas, pois podem ocorrer inúmeros problemas: alguém mal intencionado, erro no front, etc.
Com isto vale verificar o que é necessário validar: CPF/CNPJ pode ter letra? Pode ser informado email sem arroba? Algum campo pode ficar vazio? Etc.

2022-05-03 19:13 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/payer/payerCreateSave.js
> +    $.post(url, payer, function (response) {
A validação de dados no frontEnd será feito agora ou no PR com o Front?

2022-05-04 12:26 UTC, LuizFilipeLT commented on grails-app/assets/javascripts/payer/payerCreateSave.js
> +      if (response.success) {
Realizado inversão do IF para tratar o erro.

2022-05-04 17:31 UTC, LuizFilipeLT commented on grails-app/controllers/com/rocketcharger/domain/PayerController.groovy
> +            payerService.save(params)
Conforme alinhado, estaremos realizando as validações em PR's futuros.

2022-05-04 17:31 UTC, LuizFilipeLT commented on grails-app/assets/javascripts/payer/payerCreateSave.js
> +    $.post(url, payer, function (response) {
Conforme alinhado, estaremos realizando as validações em PR's futuros.

2022-05-05 11:59 UTC, Yuri-Ferrari approved these changes

2022-05-05 11:59 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/payer/payerCreateSave.js
> +$(document).ready(function () {
Vale realizar um refactor no futuro para seguir o conceito de Controller, igual foi aplicado no PR seguinte, que criou o CustomerCreateController e também separar em mais métodos

2022-05-05 12:51 UTC, LuizFilipeLT commented on grails-app/assets/javascripts/payer/payerCreateSave.js
> +$(document).ready(function () {
Realizado refatoração em branch futura.

2022-05-05 12:52 UTC, merged

2022-05-16 13:01 UTC, welingtonloh commented on grails-app/domain/com/rocketcharger/domain/Payer.groovy
> +    String district
Alguém pediu para mudar de province para district?