Adição show e edit ao payer.
LuizFilipeLT/Rocket-Charger pull request #15
Opened 2022-04-22 18:32 UTC by LuizFilipeLT

Aguardando outro PR: https://github.com/LuizFilipeLT/Rocket-Charger/pull/7](https://github.com/LuizFilipeLT/Rocket-Charger/pull/12)

Realizado inclusão do show e edit ao payer.

![adicaopayer](https://user-images.githubusercontent.com/94563876/164773861-40e4e250-afd0-4595-956e-3f848362016b.gif)

2022-05-05 12:28 UTC, Yuri-Ferrari requested changes

2022-05-05 12:28 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/customer/customerEdit.js
> +$(document).ready(function () {
Aplicar a estrutura de Controller

2022-05-05 12:28 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/index/FormController.js
>  const correctCpfLength = 11;
Esse aquivo possui esse nome mas não existe o 'FormController' dentro do mesmo, vale criá-lo aqui

2022-05-05 12:28 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/utils/CreateSaveController.js
> +function CreateSaveController() {
CreateSave é um termo 'peculiar', o objetivo desse arquivo é ter métodos padrões para todos os forms? Se sim pode muito bem ser um 'FormUtils'

2022-05-05 12:28 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/utils/loadAddress.js
> +      : "";
Essa quebra de linha está muito estranha

2022-05-05 12:28 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/utils/formEdit.js
> +$(document).ready(function () {
Vale a análise se é válido agrupar essas lógicas no 'FormController'

2022-05-05 12:28 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/utils/loadAddress.js
> +$(document).ready(function () {
Controller

2022-05-05 12:28 UTC, Yuri-Ferrari commented on grails-app/controllers/com/rocketcharger/domain/PayerController.groovy
> +    private Integer getCurrentPage() {
https://github.com/asaasdev/livro-de-elite/blob/master/best-practices/asaas.md#ordenacao-metodos

2022-05-05 12:28 UTC, Yuri-Ferrari commented on grails-app/services/com/rocketcharger/domain/PayerService.groovy
> +        if (params.id) {
EarlyReturn

2022-05-05 12:28 UTC, Yuri-Ferrari commented on grails-app/views/payer/create.gsp
> +
```suggestion
```

2022-05-05 12:28 UTC, Yuri-Ferrari commented on grails-app/views/payer/create.gsp
> +    <asset:javascript src="teste.js"/>
Acho que sobrou algo aqui

2022-05-05 12:28 UTC, Yuri-Ferrari commented on grails-app/views/payer/index.gsp
> +
```suggestion
```

2022-05-05 12:28 UTC, Yuri-Ferrari commented on grails-app/views/payer/show.gsp
> +
```suggestion
```

2022-05-05 12:28 UTC, Yuri-Ferrari commented on grails-app/views/payer/show.gsp
> +        <input type="text" name="name" id="name" placeholder="Ex: João Da Silva" value="${ payer.name}" readonly><br>
```suggestion
        <input type="text" name="name" id="name" placeholder="Ex: João Da Silva" value="${payer.name}" readonly><br>
```
Tem mais espaços sobrando abaixo

2022-05-06 13:03 UTC, Yuri-Ferrari requested changes

2022-05-06 13:03 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/index/formValidations.js
> +function fillAddress(data) {
O FillAddressController tem um método muito semelhante, unifiquem essa lógica.

2022-05-06 13:03 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/utils/formEditController.js
> +function FormEditController() {
Todo form terá um submit e poderá ser editado, vale unificar essa lógica no FormUtilsController

2022-05-06 16:21 UTC, devJoseOtavio commented on grails-app/assets/javascripts/index/formValidations.js
> +  if (!data.erro) {
Vamos refatorar estas validações futuramente e transformar em um controller

2022-05-06 16:21 UTC, devJoseOtavio commented on grails-app/assets/javascripts/index/formValidations.js
> +function fillAddress(data) {
Vamos refatorar estas validações futuramente e transformar em um controller

2022-05-06 16:38 UTC, devJoseOtavio commented on grails-app/assets/javascripts/application.js
> +//= require utils/formEditController
Todas as paginas que estão que chamam estes códigos precisam, caso venhamos a criar paginas que tenham campos que não necessitam dos imports JS,  nós criaremos outros imports com base na necessidade da página, neste carinha vamos alterar o nome para ficar mais claro oque ele está importando.

2022-05-09 15:14 UTC, Yuri-Ferrari requested changes

2022-05-10 15:06 UTC, Yuri-Ferrari requested changes

2022-05-10 15:06 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/utils/FormUtilsController.js
> +    $(document).ready(function () {
Precisa de um ready aqui? Pois quem chama o Init já está dentro de um ready.

2022-05-10 15:06 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/utils/FormUtilsController.js
> +    editBtn.addEventListener("click", hiddenBtnAndSave())
Vale um método para isto.

2022-05-16 13:18 UTC, welingtonloh requested changes

2022-05-16 13:18 UTC, welingtonloh commented on grails-app/assets/javascripts/utils/FormUtilsController.js
> +    });
Aqui vocês já tentaram pegar a referência do form, colocar numa variavel
Depois criar uma nova variavel para colocar os params, dessa maneira: var params = formReference.serializeArray();

Creio que é uma alternativa que faça vocês terem menos código

2022-05-16 13:18 UTC, welingtonloh commented on grails-app/assets/javascripts/utils/FormUtilsController.js
> +    var url = $("form").prop("action");
Conforme comentário acima, caso definissem o formReference, aqui não precisariam fazer o find novamente por form

Uma dica que dou é tentar usar a propriedade data-url na tag form, e aqui dai fazer assim:
var url = formReference.data("action"); (poderiam mudar "action" para "url") dai

2022-05-16 13:18 UTC, welingtonloh commented on grails-app/assets/javascripts/utils/FormUtilsController.js
> +    let inputsReference = $("input");
inputReferenceList

2022-05-16 13:18 UTC, welingtonloh commented on grails-app/assets/javascripts/utils/FormUtilsController.js
> +      inputsReference.each(function (i, input) {
O que o i representa? tem como não abreviarmos?

2022-05-16 13:18 UTC, welingtonloh commented on grails-app/assets/javascripts/utils/FormUtilsController.js
> +      $(".js-send-button").removeClass("hiddenBtn");
Essa classe não poderia se chamar apenas "hide" e ser utilizada em outros casos depois?

2022-05-16 13:18 UTC, welingtonloh commented on grails-app/services/com/rocketcharger/domain/PayerService.groovy
> +        Payer payer = Payer.get(params.int('id'))
Deem um confere na indentação desse método inteiro
Adiciona um linha entre a 28 e a 29

2022-05-16 13:18 UTC, welingtonloh commented on grails-app/views/payer/create.gsp
> +            <input type="text" name="state" id="state" placeholder="Estado" required><br>
Utilizem label para identificar os campos
Notem que surgiu uma despadronização nos placeholders, pq vocês não conseguem usar placeholder em tudo

2022-05-16 13:49 UTC, LuizFilipeLT commented on grails-app/services/com/rocketcharger/domain/PayerService.groovy
> +        Payer payer = Payer.get(params.int('id'))
Realizado tipagem de todos métodos em service no pr: https://github.com/LuizFilipeLT/Rocket-Charger/pull/21

aguardando merge e estamos seguindo com esta padronização de realizar a criação do método e tipar.

2022-05-16 13:58 UTC, LuizFilipeLT commented on grails-app/views/payer/create.gsp
> +            <input type="text" name="state" id="state" placeholder="Estado" required><br>
Realizado implementação de labels no pr: https://github.com/LuizFilipeLT/Rocket-Charger/pull/21

2022-05-16 16:56 UTC, LuizFilipeLT commented on grails-app/assets/javascripts/utils/FormUtilsController.js
> +      inputsReference.each(function (i, input) {
i representa index, iremos remover a abreviação.

2022-05-18 14:39 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
> +        if (!id) {
Em casos assim, pode usar earlyReturn
```suggestion
        if (!id) return
```

2022-05-18 14:39 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
> +        Customer customer = Customer.get(params.long("id"))
O id ja foi recebido através dos parâmetros, não poderia ser passado aqui direto ao invés de fazer o params.long novamente?

2022-05-18 14:39 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
> +        return customer;
👀 
```suggestion
        return customer
```

2022-05-18 14:39 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/PayerService.groovy
> +        return payer;
```suggestion
        return payer
```

2022-05-18 14:39 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/PayerService.groovy
> +        Customer customer = Customer.get(params.long("id"))
Por que foi alterado o nome desse param pra id? Num contexto de Payer usar só id não acaba ficando um pouco confuso?

2022-05-18 14:39 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/PayerService.groovy
> +        Payer payer = Payer.get(params.long("id"))
Usa o próprio id que já foi passado por parâmetro aqui

2022-05-18 19:35 UTC, LuizFilipeLT commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
> +        Customer customer = Customer.get(params.long("id"))
Poderia sim, corrigido.

2022-05-18 19:36 UTC, LuizFilipeLT commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
> +        return customer;
Acredite, já pediram pra colocar sendo que não precisava, dai já fui colocando em tudo kkkk

2022-05-19 11:14 UTC, LuizFilipeLT commented on grails-app/services/com/rocketcharger/domain/PayerService.groovy
> +        Customer customer = Customer.get(params.long("id"))
Realmente fica um pouco confuso, realizado alteração novamente.

2022-05-20 20:38 UTC, millenadias commented on grails-app/controllers/com/rocketcharger/domain/CustomerController.groovy
> +            Long id = params.long('id')
Isso se aplica a outros cenários também
```suggestion
            Long id = params.long("id")
```

2022-05-20 20:38 UTC, millenadias commented on grails-app/controllers/com/rocketcharger/domain/PayerController.groovy
> +        Integer customerId = params.long('id')
```suggestion
        Integer customerId = params.long('"d")
```

2022-05-20 20:38 UTC, millenadias commented on grails-app/controllers/com/rocketcharger/domain/PayerController.groovy
>          List <Payer> payerList = Payer.createCriteria().list(max: 10, offset: getCurrentPage()) {
Esse 10 que ta fixo ali, não poderia ser um método na BaseController? getLimit, algo assim

2022-05-20 20:38 UTC, millenadias commented on grails-app/controllers/com/rocketcharger/domain/PayerController.groovy
> +        return [customerId: params.long('id')]
```suggestion
        return [customerId: params.long("id")]
```

2022-05-20 20:38 UTC, millenadias commented on grails-app/controllers/com/rocketcharger/domain/PayerController.groovy
> +            Long id = params.long('id')
```suggestion
            Long id = params.long('"d")
```

2022-05-20 20:38 UTC, millenadias commented on grails-app/domain/com/rocketcharger/domain/Customer.groovy
> +        name size: 3..100, nullable: false
Por padrão, se não for informada nada no nullable, vai ser nullable false. Só definimos quando é pra ser nullable true, então creio que não tenha necessidade de especificar iss

2022-05-20 20:38 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
> +    def update(Long id, Map params) {
```suggestion
    public Customer update(Long id, Map params) {
```

2022-05-20 20:38 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/PayerService.groovy
> +        if (!id) {
```suggestion
        if (!id) return
```

2022-05-23 12:41 UTC, LuizFilipeLT commented on grails-app/controllers/com/rocketcharger/domain/PayerController.groovy
>          List <Payer> payerList = Payer.createCriteria().list(max: 10, offset: getCurrentPage()) {
Fizemos a BaseController com esses métodos de max e offset em outra branch.

2022-05-23 12:45 UTC, LuizFilipeLT commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
> +    def update(Long id, Map params) {
Tipagem dos métodos realizados em outra branch.

2022-05-26 20:16 UTC, Yuri-Ferrari approved these changes

2022-05-27 12:26 UTC, merged