Validacoes backend e front
LuizFilipeLT/Rocket-Charger pull request #21
Opened 2022-05-13 17:54 UTC by LuizFilipeLT

### Impacto
Prevenção de burlar o sistemas com validações backend básicas para que barre o prosseguimento do processo caso encontre algum params faltante conforme especificado no método validate e refatoração FormValidationsController para validações de frontend em toda LP com form, como create, show e edit.

### PR Predecessora
Sem PR Predecessora

### Link da tarefa no JIRA / Trello
https://lflt.atlassian.net/browse/ROC-22
https://lflt.atlassian.net/browse/ROC-29

### Prints do desenvolvimento
![code-snapshot-back1](https://user-images.githubusercontent.com/94563876/168340379-d4010244-c414-4198-9968-47c62420effd.png)
![code-snapshot-frontend1](https://user-images.githubusercontent.com/94563876/168340384-66a7d71e-4d5b-4471-94bf-5f5dcfce76f2.png)

2022-05-16 13:29 UTC, welingtonloh requested changes
Validar o PR inteiro, tem comentários que servem para mais de um ponto do código

2022-05-16 13:29 UTC, welingtonloh commented on grails-app/assets/javascripts/utils/FormUtilsController.js
> +  function bindFormSubmit() {
```suggestion
  };
  
  function bindFormSubmit() {
```

2022-05-16 13:29 UTC, welingtonloh commented on grails-app/assets/javascripts/utils/FormValidationsController.js
> +          cpfCnpjValue == "99999999999"
É estranho fazer isso para validar se cpf ou cnpj são válidos, vocês chegaram a tentar usar uma expressão regular (regex) para isso?

Conforme fizeram aqui:
var validatePostalCode = function (postalCode) {
  return /^[0-9]{8}$/.test(postalCode);
};

2022-05-16 13:29 UTC, welingtonloh commented on grails-app/controllers/com/rocketcharger/domain/CustomerController.groovy
> +            render([success: false, message: "Ocorreu um erro ao tentar salvar" + Exception] as JSON)
Isso aqui está errado, Exception com letra maiscula identifica a classe, o e identifica o objeto

2022-05-16 13:29 UTC, welingtonloh commented on grails-app/domain/com/rocketcharger/domain/Customer.groovy
> +        name nulllable: false, blank: false
Por padrão já aplica nullable false, então podem remover.

A não ser que queiram nullable true, ai sim.. precisa deixar explicito

2022-05-16 13:29 UTC, welingtonloh commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
> +    public List <Customer> index() {
```suggestion
    public List<Customer> index() {
```

2022-05-16 13:29 UTC, welingtonloh commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
> +    public Customer getCustomer(Integer id){
Por que não usar como padrão de nomes para os endpoints:
- list
- save
- show

2022-05-16 13:29 UTC, welingtonloh commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
> +        if(!params.name){
```suggestion
        if (!params.name) {
```

2022-05-16 13:29 UTC, welingtonloh commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
> +    private void validate(Map params){
```suggestion
    private void validate(Map params) {
```

2022-05-16 13:29 UTC, welingtonloh commented on grails-app/views/customer/_list.gsp
> +    <g:if test="${customerList?.size() > 0}">
```suggestion
    <g:if test="${customerList}">
```
Fica mais simples e tem o mesmo efeito

2022-05-16 13:29 UTC, welingtonloh commented on grails-app/views/customer/create.gsp
> +    <title>Create customer</title>
Deve ficar em ingles mesmo?

2022-05-16 13:29 UTC, welingtonloh commented on grails-app/views/customer/create.gsp
> +          <label for="cpfCnpj">CPF/CNPJ *</label>
Pq alguns usam ":" e outros não?

2022-05-16 17:40 UTC, LuizFilipeLT commented on grails-app/views/customer/create.gsp
> +    <title>Create customer</title>
Alterado para pt-br.

2022-05-16 17:43 UTC, LuizFilipeLT commented on grails-app/views/customer/create.gsp
> +          <label for="cpfCnpj">CPF/CNPJ *</label>
Realizado padronização para todos usarem ":"

2022-05-16 19:16 UTC, LuizFilipeLT commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
> +    public Customer getCustomer(Integer id){
realizado remoção dos métodos getCustomer e getPayer visto que já chamamos os mesmos no método show

2022-05-16 19:19 UTC, LuizFilipeLT commented on grails-app/assets/javascripts/utils/FormValidationsController.js
> +          cpfCnpjValue == "99999999999"
Iremos adicionar como melhoria futura na validação, não chegamos a testar com regex.

https://lflt.atlassian.net/browse/ROC-41

2022-05-20 21:03 UTC, millenadias commented on grails-app/controllers/com/rocketcharger/domain/PayerController.groovy
> +            render([success: false, message: 'Ocorrreu um erro: ' + e.message ]  as JSON)
Isso aparece em tela?
```suggestion
            render([success: false, message: 'Ocorreu um erro: ' + e.message ]  as JSON)
```

2022-05-20 21:04 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
> +            throw new Exception('Erro no registro do nome informado.')
Não é legal a gente lançar Exceptions assim, cria um DomainUtils, e adiciona erros na domain, nesse caso aqui na Customer. Podemos bater um papo sobre dai explico e mostro como daria pra fazer

2022-05-20 21:05 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/PayerService.groovy
> +        return payer;
```suggestion
        return payer
```

2022-05-20 21:05 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/PayerService.groovy
>          Customer customer = Customer.get(params.int('customerId'))
Evita o uso de aspas simples
```suggestion
        Customer customer = Customer.get(params.int("customerId"))
```

2022-05-20 21:09 UTC, millenadias commented on grails-app/views/customer/_list.gsp
> +              >
Ficou perdido aqui

2022-05-23 17:47 UTC, LuizFilipeLT commented on grails-app/controllers/com/rocketcharger/domain/CustomerController.groovy
> +            render([success: false, message: "Ocorrreu um erro: " + e.message] as JSON)
No caso a exception que vem a ser exibida é pega no método validate do CustomerService, assim não exibimos algo técnico em tela.

2022-05-26 20:35 UTC, Yuri-Ferrari requested changes
Esse PR tem muitas alterações repetidas em outro PR, após o merge do PR anterior revisar o impacto neste.

2022-05-26 20:35 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/utils/FormValidationsController.js
> +  this.init = function () {
Esse init engloba todo o controller.
O correto seria conter no init apenas as chamadas de métodos necessários na inicialização do Controller, não os métodos em si.

2022-05-30 14:53 UTC, Yuri-Ferrari requested changes

2022-05-30 14:53 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/utils/FormValidationsController.js
> +    correctCnpjLength;
Essas linhas não são necessárias

2022-05-30 14:53 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/utils/FormValidationsController.js
> +    });
Criem métodos que encapsulem essas lógicas

2022-05-31 12:42 UTC, LuizFilipeLT commented on grails-app/views/customer/create.gsp
> +    ></script>
Sim, somente esta sendo utilizado nas páginas de create.

2022-05-31 17:57 UTC, LuizFilipeLT commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
> +    public Customer validate(Map params) {
Realizado criação de ValidateUtils com regex para filtragens.

2022-06-01 16:43 UTC, Yuri-Ferrari requested changes

2022-06-01 16:43 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/utils/FormValidationsController.js
> +      }
EarlyReturn

2022-06-01 16:43 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/utils/FormValidationsController.js
> +  function checkName() {
Como o nome do controller remete a validação, vale alterar a nomenclatura dos métodos para seguir esta linha de pensamento, como `validateName`

2022-06-01 16:43 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/utils/FormValidationsController.js
> +    emailListener();
Só pra ficarem por dentro dos padrões Asaas, para estes casos nós utilizamos o padrão `bindSubmitForm`, `bindInputName`, mas não irei cobrar esse padrão, fica a critério de vocês usar ou manter o atual.

2022-06-01 16:43 UTC, Yuri-Ferrari commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
> +         ValidateUtils.validatePostalCode(params.postalCode)
Se alguma dessas validações retornar false o customer será salvo, o que é um problema.

2022-06-01 16:43 UTC, Yuri-Ferrari commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
>           Customer customer = new Customer(params)
Alterar para não utilizar construtor

2022-06-01 16:43 UTC, Yuri-Ferrari commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
> +    public Customer validate(Map params) {
Esse método não será mais usado na criação ou alteração?

2022-06-01 16:43 UTC, Yuri-Ferrari commented on grails-app/services/com/rocketcharger/domain/PayerService.groovy
> +        ValidateUtils.validatePostalCode(params.postalCode)
Mesmos comentários referentes ao CustomerService

2022-06-01 16:43 UTC, Yuri-Ferrari commented on grails-app/services/com/rocketcharger/domain/PayerService.groovy
> +    public Payer validate(Map params) {
Mesmo comentário referente ao CustomerService

2022-06-01 16:43 UTC, Yuri-Ferrari commented on grails-app/utils/ValidateUtils.groovy
> +        return false
Utilizar earlyReturn

2022-06-02 16:49 UTC, LuizFilipeLT commented on grails-app/assets/javascripts/utils/FormValidationsController.js
> +    emailListener();
É bom tentarmos adotar o máximo possível do padrão, para já ir se acostumando.

2022-06-02 18:44 UTC, LuizFilipeLT commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
> +         ValidateUtils.validatePostalCode(params.postalCode)
Realizado correções.

2022-06-02 18:53 UTC, LuizFilipeLT commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
> +    public Customer validate(Map params) {
Foi realizado correção, será utilizado.

2022-06-07 12:25 UTC, Yuri-Ferrari approved these changes

2022-06-07 14:33 UTC, merged