Criando payment
LuizFilipeLT/Rocket-Charger pull request #23
Opened 2022-05-17 14:54 UTC by devJoseOtavio

### Impacto

Foi criado o CRUD do payment contendo o modelo de base MVC visando criar uma cobrança, também foi aplicado a ligação das ID's do Customer e Payer no Payment fazendo com que a cobrança tenha a quem ser redirecionada.

### Link da tarefa no JIRA / Trello

https://lflt.atlassian.net/browse/ROC-13
https://lflt.atlassian.net/browse/ROC-32
https://lflt.atlassian.net/browse/ROC-14
https://lflt.atlassian.net/browse/ROC-6

### Gif do desenvolvimento
![payment](https://user-images.githubusercontent.com/101358660/168841576-3b34de4b-e344-4b54-b74d-02b9e6b3b9da.gif)

2022-05-20 21:26 UTC, millenadias commented on grails-app/controllers/com/rocketcharger/domain/PaymentController.groovy
> +import grails.validation.ValidationException
Separa os imports internos e externos com uma linha em branco
```suggestion

import grails.validation.ValidationException
```

2022-05-20 21:26 UTC, millenadias commented on grails-app/controllers/com/rocketcharger/domain/PaymentController.groovy
> +class PaymentController {
```suggestion
class PaymentController extends BaseController {
```

2022-05-20 21:26 UTC, millenadias commented on grails-app/controllers/com/rocketcharger/domain/PaymentController.groovy
> +        List<Payment> paymentList = Payment.createCriteria().list(max: 10, offset: getCurrentPage()) {
Ao invés de pegar esse 10 fixo, cria e usa um método na BaseController.

2022-05-20 21:26 UTC, millenadias commented on grails-app/controllers/com/rocketcharger/domain/PaymentController.groovy
> +        Long customerId = params.long("id")
Acho que estão num contexto de payment colocar id fica meio confuso pra saber id do que exatamente. Colocando customerId fica claro. 
```suggestion
        Long customerId = params.long("customerId")
```

2022-05-20 21:26 UTC, millenadias commented on grails-app/controllers/com/rocketcharger/domain/PaymentController.groovy
> +        [payerList: payerList, totalCount: Payer.count()]
Tem isso e depois um return, por que?

2022-05-20 21:26 UTC, millenadias commented on grails-app/controllers/com/rocketcharger/domain/PaymentController.groovy
> +            println e
```suggestion
```

2022-05-20 21:26 UTC, millenadias commented on grails-app/domain/com/rocketcharger/domain/Payment.groovy
> +    static constraints = {
Se não tiver nada dentro, pode remover

2022-05-20 21:26 UTC, millenadias commented on grails-app/controllers/com/rocketcharger/domain/PaymentController.groovy
> +    private Integer getCurrentPage() {
Coloca isso no BaseController, dai da pra usar em todas as controllers.

2022-05-20 21:26 UTC, millenadias commented on grails-app/domain/com/rocketcharger/domain/Payment.groovy
> +class Payment {
Essa domain não deveria conter a data de pagamento? Em breve será implementado o pagamento de fato, o correto seria armazenar a data de pagamento

2022-05-20 21:26 UTC, millenadias commented on grails-app/domain/com/rocketcharger/domain/Payment.groovy
> +    String dueDate
Precisa ser uma String?
```suggestion
    Date dueDate
```

2022-05-20 21:26 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
>          return Customer.get(id)
Não precisa criar um método pra isso, já é bem sucinto. Nos lugares onde é chamado, pode passar o próprio Customer.get(id), fica melhor que fazer customerServices.getCustomer(id)

2022-05-20 21:26 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/CustomerService.groovy
>          return;
```suggestion
        return
```

2022-05-20 21:26 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/PayerService.groovy
> +    public Payer save(Map params) {
O método está declarado para retornar um Payer mas não está retornando. Faz um return no payer

2022-05-20 21:26 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/PayerService.groovy
> +    public List<Payer> index() {
Index não é um bom nome para usar no service, coloca list

2022-05-20 21:26 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/PayerService.groovy
> +        return payer;
```suggestion
        return payer
```

2022-05-20 21:26 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/PaymentService.groovy
> +import com.rocketcharger.domain.customer.Customer
```suggestion
import com.rocketcharger.domain.customer.Customer

```

2022-05-20 21:26 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/PaymentService.groovy
> +    public List<Payment> index() {
index não é um bom nome para estar no service, coloca como list

2022-05-20 21:26 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/PaymentService.groovy
> +        return Payment.get(id)
Igual ao caso do Payer, não precisa criar um método para isso, nos lugares onde está sendo chamado pode passar diretamente o Payment.get(id), fica melhor do que paymentService.getPayment(id)

2022-05-20 21:26 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/PaymentService.groovy
> +        return payment;
```suggestion
        return payment
```

2022-05-20 21:26 UTC, millenadias commented on grails-app/views/payer/_list.gsp
> +            </td>
Ta fechando a mais? Se não tiver, tem algo errado com a identação

2022-05-20 21:26 UTC, millenadias commented on grails-app/views/payment/_list.gsp
> +    <g:if test="${paymentList?.size() > 0}">
```suggestion
    <g:if test="${paymentList}">
```

2022-05-20 21:26 UTC, millenadias commented on grails-app/controllers/com/rocketcharger/domain/PaymentController.groovy
> +            render([success: false, message: "Ocorreu um erro"] as JSON)
Vai ser exibido alguma mensagem? Já analisaram a possiblidade de usar flash.message? Podemos bater um papo sobre caso tenham interesse de aplicar

2022-05-23 12:47 UTC, devJoseOtavio commented on grails-app/controllers/com/rocketcharger/domain/PaymentController.groovy
> +class PaymentController {
Não utilizamos o base controller na branch criando payment, nesta branch focamos em fazer o CRUD do payment com os métodos de create, save, show e ligação ao payer

O BaseController foi aplicado na branch finalizando payment

2022-05-23 13:05 UTC, devJoseOtavio commented on grails-app/controllers/com/rocketcharger/domain/PaymentController.groovy
> +        [payerList: payerList, totalCount: Payer.count()]
Apaguei o primeiro agrupamento de colchetes, vi que não era necessário e conseguia chamar ele no return diminuindo linhas de código

2022-05-23 14:03 UTC, LuizFilipeLT commented on grails-app/controllers/com/rocketcharger/domain/PaymentController.groovy
> +    private Integer getCurrentPage() {
Método foi passado para a BaseController na branch Finalizando-payment, a mesma ainda n possui PR aberto.

2022-05-23 14:05 UTC, LuizFilipeLT commented on grails-app/domain/com/rocketcharger/domain/Payment.groovy
> +    String dueDate
Como nesta branch estavamos realizando os testes para criação, todos os atributos devem ser String para podermos utilizar um new Payment(params), sem especificar atributo por atributo com seu tipo, esta mudança foi realizada na branch finalizando-Payment, a qual não possui pr aberto até o momento.

2022-05-23 14:51 UTC, LuizFilipeLT commented on grails-app/domain/com/rocketcharger/domain/Payment.groovy
> +class Payment {
Iremos implementar esta data de pagamento na branch finalizando-payment.

2022-05-23 17:33 UTC, LuizFilipeLT commented on grails-app/controllers/com/rocketcharger/domain/PaymentController.groovy
> +            render([success: false, message: "Ocorreu um erro"] as JSON)
Será renderizado a exception "e", só não realizamos essa alteração nesta branch, mas já se encontra nas validações-backend-e-front.

2022-05-27 21:04 UTC, millenadias commented on grails-app/controllers/com/rocketcharger/domain/PaymentController.groovy
> +        [paymentList: paymentList, totalCount: Payment.count()]
```suggestion
        return [paymentList: paymentList, totalCount: Payment.count()]
```

2022-05-27 21:04 UTC, millenadias commented on grails-app/controllers/com/rocketcharger/domain/PaymentController.groovy
> +    private Integer getCurrentPage() {
Cria um BaseController e coloca esse método la, faz teu controller ter o extends BaseController, dai vc pode usar esse mesmo método em várias controllers

2022-05-27 21:04 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/PaymentService.groovy
> +    public List<Payment> index() {
Não fica melhor? 
```suggestion
    public List<Payment> list() {
```

2022-05-27 21:04 UTC, millenadias commented on grails-app/services/com/rocketcharger/domain/PaymentService.groovy
> +        if (!params.id) {
```suggestion
        if (!params.id) return
```

2022-05-30 15:04 UTC, Yuri-Ferrari requested changes

2022-05-30 15:04 UTC, Yuri-Ferrari commented on grails-app/services/com/rocketcharger/domain/PaymentService.groovy
> +        Payment payment = new Payment(params)
Entidades de domínio não devem ter construtores e creio que esta não tem.

2022-05-30 15:04 UTC, Yuri-Ferrari commented on grails-app/controllers/com/rocketcharger/domain/PaymentController.groovy
> +    }
É necessário criar as validações para criação e atualização

2022-05-30 18:47 UTC, LuizFilipeLT commented on grails-app/controllers/com/rocketcharger/domain/PayerController.groovy
> +        List<Payer> payerList = Payer.createCriteria().list(max: 10, offset: getCurrentPage()) {
Realizado criação.

2022-05-30 18:55 UTC, LuizFilipeLT commented on grails-app/controllers/com/rocketcharger/domain/PaymentController.groovy
> +    }
As validações de payment estão sendo realizadas em outra branch que terá um PR futuro.

2022-06-01 17:07 UTC, Yuri-Ferrari commented on src/main/groovy/com/rocketcharger/base/BaseController.groovy
> +
```suggestion
```

2022-06-01 17:07 UTC, Yuri-Ferrari commented on src/main/groovy/com/rocketcharger/base/BaseController.groovy
> +    private Integer returnSizeLimitPage() {
```suggestion
    private Integer getSizeLimitPage() {
```

2022-06-01 18:47 UTC, LuizFilipeLT commented on grails-app/services/com/rocketcharger/domain/PaymentService.groovy
> +        Payment payment = new Payment()
Será desenvolvido as validações para que tenha um valor, método de pagamento, status, data de vencimento todos campos sendo obrigatórios e que o método de pagamento e status sejam condizentes com os valores declarados no seu devido enum.

2022-06-02 17:40 UTC, Yuri-Ferrari approved these changes

2022-06-03 03:24 UTC, jpdev01 commented on grails-app/assets/javascripts/utils/formPaymentController.js
> +    $("form").on("submit", function (e) {
Se fizer $("form") e tiver dois formulários na mesma página ele vai se perder, recomendo trabalhar com classe.

2022-06-03 03:24 UTC, jpdev01 commented on grails-app/assets/javascripts/utils/formPaymentController.js
> +        alert(`Erro ao realizar requisição, contate o administrador..`);
O response deveria trazer o erro que aconteceu

2022-06-07 14:46 UTC, merged