Aplicando spring security
LuizFilipeLT/Rocket-Charger pull request #33
Opened 2022-06-08 17:02 UTC by devJoseOtavio

### Impacto
Aplicação do Spring Security no projeto para ter uma interface de register, login e logout e para não dar acesso a usuários que não possuem contas, também é aplicado um role para definir se o usuário é administrador ou apenas um usuário comum fazendo com que o administrador tenha algumas funções extras.

### PR Predecessora
Sem PR predecessora

### Link da tarefa no JIRA / Trello
https://lflt.atlassian.net/jira/software/projects/ROC/boards/1?selectedIssue=ROC-61

### Gif do desenvolvimento
![springSecurity](https://user-images.githubusercontent.com/101358660/172672636-e64ce380-dcad-47e6-a0f1-b9597d71f676.gif)

2022-06-10 21:09 UTC, Yuri-Ferrari requested changes

2022-06-10 21:09 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/spring/FormRegisterAndLoginController.js
> +  function bindFormSubmit() {
```suggestion

  function bindFormSubmit() {
```

2022-06-10 21:09 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/spring/FormRegisterAndLoginController.js
> +    $.post(url, params, function (response) {
```suggestion
    $.post(url, params, function(response) {
```

2022-06-10 21:09 UTC, Yuri-Ferrari commented on grails-app/controllers/com/rocketcharger/domain/CustomUserDetails.groovy
> +            credentialsNonExpired, accountNonLocked, authorities, id)
Deixa tudo isto em uma linha pra cada, além dos tipos coloquem com letra maiúscula. Outros pontos do PR também sofrem deste problema.

2022-06-10 21:09 UTC, Yuri-Ferrari commented on grails-app/controllers/com/rocketcharger/domain/CustomUserDetails.groovy
> +import com.rocketcharger.domain.CustomUserDetails
Esses imports não são necessários

2022-06-10 21:09 UTC, Yuri-Ferrari commented on grails-app/controllers/com/rocketcharger/domain/RegisterController.groovy
> +            flash.message = "Password and Re-Password not match"
A liguagem com o usuário deve ser em pt-BR

2022-06-10 21:09 UTC, Yuri-Ferrari commented on grails-app/controllers/com/rocketcharger/domain/RegisterController.groovy
> +                def role = Role.get(params.role.id)
Tipem as variáveis

2022-06-10 21:09 UTC, Yuri-Ferrari commented on grails-app/controllers/com/rocketcharger/domain/RegisterController.groovy
> +import com.rocketcharger.domain.CustomUserDetails
Revisar imports, muitos não são usados

2022-06-10 21:09 UTC, Yuri-Ferrari commented on grails-app/domain/com/rocketcharger/domain/UserRole.groovy
> +package com.rocketcharger.domain
Ajustar identação neste e em outros arquivos

2022-06-10 21:09 UTC, Yuri-Ferrari commented on grails-app/views/login/auth.gsp
> +                  <label for="username">Username</label>
Termos em pt-BR, ajustar outros pontos do PR também.

2022-06-10 21:09 UTC, Yuri-Ferrari commented on grails-app/views/login/auth.gsp
> +    </script>
Isto deve ficar em um arquivo JS

2022-06-13 16:21 UTC, devJoseOtavio commented on grails-app/controllers/com/rocketcharger/domain/RegisterController.groovy
> +            flash.message = "Password and Re-Password not match"
Foi criado uma segunda branch com o nome refatorando-springSecurity e lá fizemos as atualizações de registro e login para melhorar a interação do user com a nossa plataforma, colocando em português e etc

2022-06-13 16:22 UTC, devJoseOtavio commented on grails-app/controllers/com/rocketcharger/domain/RegisterController.groovy
> +                def role = Role.get(params.role.id)
Foi criado uma segunda branch com o nome refatorando-springSecurity e lá criamos um service para apresentar nossa regra de négocio, estas linhas já não vão mais existir lá

2022-06-13 22:27 UTC, devJoseOtavio commented on grails-app/domain/com/rocketcharger/domain/UserRole.groovy
> +package com.rocketcharger.domain
Foi corrigido na nova branch

2022-06-15 17:26 UTC, Yuri-Ferrari requested changes

2022-06-15 17:26 UTC, Yuri-Ferrari commented on grails-app/services/com/rocketcharger/domain/CustomUserDetailsService.groovy
> +      def authorities = roles.collect {
Tipar

2022-06-15 17:26 UTC, Yuri-Ferrari commented on grails-app/domain/com/rocketcharger/domain/UserRole.groovy
> +        if (user) {
earlyReturn

2022-06-15 17:26 UTC, Yuri-Ferrari commented on grails-app/controllers/com/rocketcharger/domain/RegisterController.groovy
> +        } else {
Podem remover o else, afinal o IF acima é um earlyReturn

2022-06-15 17:26 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/applications/applicationPostRegisterAndLogin.js
> +//= require spring/FormRegisterAndLogin
Esse arquivo existe?

2022-06-15 17:26 UTC, Yuri-Ferrari commented on grails-app/assets/javascripts/spring/FormRegisterAndLoginController.js
> +function FormUtilsController() {
Nome difere do nome do arquivo

2022-06-17 11:48 UTC, marlon407 approved these changes

2022-06-17 12:32 UTC, merged